In [1]:
# Importando a biblioteca numpy e default_timer
import numpy as np
from timeit import default_timer as timer

In [2]:
def GaussJordan(A, b):
    '''
    Executa o método de Gauss-Jordan para resolver o sistema linear Ax=b 
    transformando a matriz A na matriz identidade.
    Parâmetros de entrada: A é uma matriz quadrada de ordem n e b é o vetor constante.
    Saída: vetor solução x
    '''
    n = len(A)
    
    start = timer()
    for k in range (0,n):
        for j in range(k+1,n):
            A[k][j] = A[k][j]/A[k][k]
        b[k] = b[k]/A[k][k]
        A[k][k] = 1
        for i in range(0,n):
            if i!= k:
                m = -A[i][k]/A[k][k]
                for j in range (k+1,n):
                    A[i][j] = m*A[k][j] + A[i][j]
                b[i] = m*b[k] +b[i]
                A[i][k] = 0
    end = timer()
    
    print("\nSolução encontrada:")
    print(b[:])
    
    det = Determinant(A)
    print("\nDeterminante: ", det)
    
    print("\nTempo de execução total aproximado: %e segundos" % (end - start))
    print("Tempo aproximado por iteração: %e segundos" % ((end - start)/n))
    
    return b

def Determinant(A):
    n = len(A)
    det = 1
    for k in range(0, n):
        det *= A[k][k]
    return det

In [3]:
def Identity(n):
    '''Cria uma matriz identidade de ordem n.
    Parâmetros de entrada:  n é a ordem da matriz.
    Saída: matriz identidade de ordem n
    '''
    I = n*[0]
    for i in range(n):
        I[i] = n*[0]
    
    for i in range(0, n):
        I[i][i] = 1
    return I

def Inverse(A):
    '''
    Executa o método de Gauss-Jordan para calcular a matriz inversa de A.
    Parâmetros de entrada: A é uma matriz quadrada de ordem n.
    Saída: Inv é a matriz inversa de A.
    '''
    n = len(A)
    Inv = Identity(n)
     
    start = timer()
    # Para cada etapa k
    for k in range(0, n):
        if abs(A[k][k]) > 0:
            m = A[k][k]
            
            for i in range(k, n):
                A[k][i] = A[k][i]/m
                Inv[k][i] = Inv[k][i]/m
            
        if A[k][k] < 0:
            for i in range(0, n):
                A[k][i] = A[k][i]*-1
                Inv[k][i] = Inv[k][i]*-1
            
        # Para cada linha i
        for i in range(k+1, n):
            # Calcula o fator m
            m = -A[i][k]/A[k][k]
            # Atualiza a linha i da matriz, percorrendo todas as colunas j
            for j in range(0, n):
                A[i][j] = A[i][j] + m*A[k][j]
                Inv[i][j] = Inv[i][j] + m*Inv[k][j]
                    
        for i in range(0, k): 
            # Calcula o fator m
            m = -A[i][k]/A[k][k]
            # Atualiza a linha i da matriz, percorrendo todas as colunas j
            for j in range(0, n):
                A[i][j] = A[i][j] + m*A[k][j]
                Inv[i][j] = Inv[i][j] + m*Inv[k][j]
    end = timer()
    
    print("Matriz Inversa: \n%s" % np.array(Inv))
    
    det = Determinant(A)
    print("\nDeterminante: ", det)
    
    print("\nTempo de execução total aproximado: %e segundos" % (end - start))
    print("Tempo aproximado por iteração: %e segundos" % ((end - start)/n))
    
    return Inv

In [4]:
#Ax=b

# Definindo a Matriz A 
A = [[2,  2, 1,  1],
     [1, -1, 2, -1],
     [3, 2, -3, -2],
     [4, 3,  2,  1]]
print("Matriz A: \n%s" % np.array(A))

# Definindo o Vetor b
b = [7, 1, 4, 12]
print("\nVetor b : \n", np.array(b))

print("-"*20, "Método Aplicado", "-"*20)

# Chama as função passando os parâmetros
x = GaussJordan(A, b)

Matriz A: 
[[ 2  2  1  1]
 [ 1 -1  2 -1]
 [ 3  2 -3 -2]
 [ 4  3  2  1]]

Vetor b : 
 [ 7  1  4 12]
-------------------- Método Aplicado --------------------

Solução encontrada:
[1.0, 2.0, 1.0, 0.0]

Determinante:  1

Tempo de execução total aproximado: 6.650566e-05 segundos
Tempo aproximado por iteração: 1.662641e-05 segundos


In [5]:
# Ax=b

# Definindo a Matriz A 
A = [[2,  2, 1,  1],
     [1, -1, 2, -1],
     [3, 2, -3, -2],
     [4, 3,  2,  1]]
print("Matriz A: \n%s" % np.array(A))

# Definindo o Vetor b
b = [7, 1, 4, 12]
print("\n Vetor b : \n", np.array(b))

# Concatenando Matriz A com Vetor b: Ab
#Ab = np.hstack((A, b))
i = Identity(len(A))
print("\n Identidade : \n%s" % np.array(i))

print("-"*20, "Método Aplicado", "-"*20)

# Chama as funções passando os parâmetros
y = Inverse(A)

Matriz A: 
[[ 2  2  1  1]
 [ 1 -1  2 -1]
 [ 3  2 -3 -2]
 [ 4  3  2  1]]

 Vetor b : 
 [ 7  1  4 12]

 Identidade : 
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
-------------------- Método Aplicado --------------------
Matriz Inversa: 
[[-0.11904762  0.33333333  0.10884354  6.33333333]
 [ 2.57142857  0.125       0.02040816 -8.        ]
 [ 0.0952381  -0.04166667 -0.11564626 -3.66666667]
 [-4.         -0.875      -0.14285714  7.        ]]

Determinante:  1.0

Tempo de execução total aproximado: 1.888432e-04 segundos
Tempo aproximado por iteração: 4.721081e-05 segundos
