In [1]:
# Importando a biblioteca numpy e default_timer
import numpy as np
from timeit import default_timer as timer

In [2]:
def RetroSubstitutions(A, b):
    
    A = np.array(np.mat(A), dtype=float)
    b = np.array(np.mat(b), dtype=float)
    
    N = A.shape[0]
    y = np.zeros(N)

    print("Matriz A:")
    print(A)
    print("\n Vetor b:")
    print(b)
    
    start = timer()
    
    for i in range(N-1,-1,-1):
        s = sum([A[i][j]*y[j] for j in range(i+1,N)])
        y[i] = (b[0, i] - s )/A[i][i]

    end = timer()

    print("\nTempo de execução total aproximado: %e segundos" % (end - start))
    print("Tempo aproximado por iteração: %e segundos" % ((end - start)/N))

    print("\nSolução encontrada:")
    print(y[:,None])

    return y

In [3]:
def Gauss(A, b):
    '''Executa o método da eliminação de Gauss para resolver o sistema  linear Ax=b 
    transformando o sistema em um sistema triangular superior equivalente.
    Parâmetros de entrada: A é uma matriz quadrada de ordem n e b é o vetor constante.
    Saída: vetor x
    '''
    ## n é a ordem da matriz A
    n = len(A)
 
    ## Para cada etapa k
    for k in range(0, n):
        ## Para cada linha i
        for i in range(k+1, n):
            ## Calcula o fator m
            m = -A[i][k]/A[k][k]
            ## Atualiza a linha i da matriz, percorrendo todas as colunas j
            for j in range(0, n):
                A[i][j] = A[i][j] + m*A[k][j]
            # Atualiza o vetor b na linha i
            b[i] = b[i] + m*b[k]

            ## Zera o elemento Aik
            A[i][k] = 0

    # Resolve o sistema triangular superior usando as substituições retroativas
    x = RetroSubstitutions(A, b)
    return x

def Determinant(A):
    n = len(A)
    det = 1
    for k in range(0, n):
        det *= A[k][k]
    return det

In [4]:
#Ax=b

# Definindo a Matriz A 
A = [[2,  2, 1,  1],
     [1, -1, 2, -1],
     [3, 2, -3, -2],
     [4, 3,  2,  1]]
print("Matriz A:  \n%s" % np.array(A))

# Definindo o Vetor b
b = [7, 1, 4, 12]
print("\n Vetor b : \n", np.array(b))

# Concatenando Matriz A com Vetor b: Ab
#Ab = np.hstack((A, b))

print("-"*20, "Método Aplicado", "-"*20)

# Chama as funções passando os parâmetros
x = Gauss(A, b)
det = Determinant(A)
print("Determinante: ", det)

Matriz A:  
[[ 2  2  1  1]
 [ 1 -1  2 -1]
 [ 3  2 -3 -2]
 [ 4  3  2  1]]

 Vetor b : 
 [ 7  1  4 12]
-------------------- Método Aplicado --------------------
Matriz A:
[[ 2.          2.          1.          1.        ]
 [ 0.         -2.          1.5        -1.5       ]
 [ 0.          0.         -5.25       -2.75      ]
 [ 0.          0.          0.          0.14285714]]

 Vetor b:
[[ 7.   -2.5  -5.25  0.  ]]

Tempo de execução total aproximado: 1.543588e-04 segundos
Tempo aproximado por iteração: 3.858970e-05 segundos

Solução encontrada:
[[1.]
 [2.]
 [1.]
 [0.]]
Determinante:  3.0
