In [1]:
# Importando a biblioteca numpy e default_timer
import numpy as np
from timeit import default_timer as timer

In [2]:
def SuccSubstitutions(A, b):
    '''
    Executa o método das substituições sucessivas para resolver o sistema
    linear triangular inferior Ax=b.
    Parâmetros de entrada: A é uma matriz triangular inferior e b é o vetor constante.
    Saída: vetor x
    '''

    A = np.array(np.mat(A),dtype=float)
    b = np.array(np.mat(b),dtype=float)

    N = A.shape[0]
    y = np.zeros(N)

    start = timer()

    for i in range(N):
        s = sum([A[i][j]*y[j] for j in range(i-1,-1,-1)])
        y[i] = (b[0, i] - s )/A[i][i]

    end = timer()

    return y

def RetroSubstitutions(A, b):

    A = np.array(np.mat(A), dtype=float)
    b = np.array(np.mat(b), dtype=float)

    N = A.shape[0]
    x = np.zeros(N)

    start = timer()

    for i in range(N-1,-1,-1):
        s = sum([A[i][j]*x[j] for j in range(i+1,N)])
        x[i] = (b[0, i] - s )/A[i][i]

    end = timer()

    print("\nSolução Encontrada:")
    print(x[:,None])

    return x

In [3]:
def Identity(n):
    '''
    Cria uma matriz identidade de ordem n.
    Parâmetros de entrada:  n é a ordem da matriz.
    Saída: matriz identidade de ordem n
    '''
    I = n*[0]
    for i in range(n):
        I[i] = n*[0]

    for i in range(0, n):
        I[i][i] = 1
    return I

def LU(A):
    '''
    Decompõe a matriz A no produto de duas matrizes L e U. Onde L é uma matriz
    triangular inferior unitária e U é uma matriz triangular superior.
    Parâmetros de entrada: A é uma matriz quadrada de ordem n.
    Saída: (L,U) tupla com as matrizes L e U
    '''
    n = len(A)

    # Inicializa a matriz L com a matriz identidade
    L = Identity(n)

    # n é a ordem da matriz A
    n = len(A)

    # Para cada etapa k
    for k in range(0, n):
        # Para cada linha i
        for i in range(k+1, n):
            # Calcula o fator m
            m = -A[i][k]/A[k][k]
            L[i][k] = m*-1

            # Atualiza a linha i da matriz, percorrendo todas as colunas j
            for j in range(0, n):
                A[i][j] = A[i][j] + m*A[k][j]
            # Zera o elemento Aik
            A[i][k] = 0

    return (L, A)

In [4]:
def SolveLU(A, b):
    '''
    Executa o método LU para resolver o sistema  linear Ax=b.
    Esse método inicialmente decompõe a matriz em L e U e depois resolve os
    dois sistemas lineares triangulares.
    Parâmetros de entrada: A é uma matriz quadrada de ordem n e b é o vetor constante.
    Saída: vetor x solução do sistema.
    '''

    (L, U) = LU(A)
    y = SuccSubstitutions(L, b)
    x = RetroSubstitutions(U, y)

    return x

In [5]:
# Ax=b
# Definindo a Matriz A
A = [[2,  2, 1,  1],
     [1, -1, 2, -1],
     [3, 2, -3, -2],
     [4, 3,  2,  1]]
print("Matriz A:  \n%s" % np.array(A))

# Definindo o Vetor b
b = [7, 1, 4, 12]
print("\n Vetor b : \n", np.array(b))

print("-"*20, "Método Aplicado", "-"*20)

x = SolveLU(A, b)

Matriz A:  
[[ 2  2  1  1]
 [ 1 -1  2 -1]
 [ 3  2 -3 -2]
 [ 4  3  2  1]]

 Vetor b : 
 [ 7  1  4 12]
-------------------- Método Aplicado --------------------

Solução Encontrada:
[[1.]
 [2.]
 [1.]
 [0.]]


In [6]:
# Ax=b
# Definindo a Matriz A
A = [[2,  2, 1,  1],
     [1, -1, 2, -1],
     [3, 2, -3, -2],
     [4, 3,  2,  1]]
print("Matriz A:  \n%s" % np.array(A))

# Definindo o Vetor b
b = [7, 1, 4, 12]
print("\n Vetor b : \n", np.array(b))

print("-"*20, "Método Aplicado", "-"*20)

(L, U) = LU(A)
print("\nMatriz L: \n%s" % np.array(L))
print("\nMatriz U: \n%s" % np.array(U))

Matriz A:  
[[ 2  2  1  1]
 [ 1 -1  2 -1]
 [ 3  2 -3 -2]
 [ 4  3  2  1]]

 Vetor b : 
 [ 7  1  4 12]
-------------------- Método Aplicado --------------------

Matriz L: 
[[1.         0.         0.         0.        ]
 [0.5        1.         0.         0.        ]
 [1.5        0.5        1.         0.        ]
 [2.         0.5        0.14285714 1.        ]]

Matriz U: 
[[ 2.          2.          1.          1.        ]
 [ 0.         -2.          1.5        -1.5       ]
 [ 0.          0.         -5.25       -2.75      ]
 [ 0.          0.          0.          0.14285714]]
